### ISSUE TITLE
Overlay positioning incorrect in landscape mode -- iOS 8

### ISSUE THREAD

**Issue by SquaredTiki** [myell0w/MTStatusBarOverlay#88]
In iOS 8 when the device is rotated (from portrait to landscape for example) the positioning and width of the overlay does not change, rather it keeps the same width as in portrait mode. This results in the overlay being shifted across to the right, showing some of the status bar

**Comment by skumawat** [comment]
Hello, When we display message on status bar using MTStatusbaroverlay class then message doesn't display properly in portrait & landscape mode on iOS 9 devices. Its working fine on iOS 8 or lower devices.
