### ISSUE TITLE
iOS 9 Black Screen Issue

### ISSUE THREAD

**Issue by suhailrashidbhat** [myell0w/MTStatusBarOverlay#97]
While Appearing Status bar the screen gets black on iOS 9

**Comment by nihilenz** [comment]
Hello, please try this change, it helps in my case:
nihilenz@565488e

**Comment by suhailrashidbhat** [comment]
:+1: 
Thanks it worked!

**Comment by xiaoMingChina** [comment]
thanks

**Comment by Emmo213** [comment]
This helped but didn't completely fix my issue. Now the status bar will be shown correctly on iOS 6, 7, and 8, but on iOS 9 it is only shown on the iPad - it doesn't show on the iPod.

**Comment by shweta-techjini** [comment]
Thanks it helped me!!

**Comment by hlung** [comment]
:+1: cool! how did you managed to know that using `-init:` instead of `-initWithFrame:` will fix the black screen problem??

**Comment by skumawat** [comment]
When we display message on status bar using MTStatusbaroverlay class then message doesn't display properly in portrait & landscape mode on iOS 9 devices. Its working fine on iOS 8 or lower devices.
![simulator screen shot 04-dec-2015 2 38 46 pm](https://cloud.githubusercontent.com/assets/8231279/11585866/0e390a06-9a95-11e5-893b-7f5287b520a9.png)
![simulator screen shot 04-dec-2015 2 38 51 pm](https://cloud.githubusercontent.com/assets/8231279/11585867/0e3ab2d4-9a95-11e5-96ba-2320a30a1891.png)
![simulator screen shot 04-dec-2015 2 39 04 pm](https://cloud.githubusercontent.com/assets/8231279/11585868/0e3ac59e-9a95-11e5-8ffa-fd3af00f509b.png)

**Comment by skumawat** [comment]
Any update regarding above issue?
